Tweak JSHint.
* Configure it to expect NodeJS (so it won't warn about 'use strict').
* Make it explicitly say if there it passed/failed.
* Document how to run all tests at the same time.

diff --git a/tests/jshint b/tests/jshint
--- a/tests/jshint
+++ b/tests/jshint
@@ -1,3 +1,10 @@
 #!/usr/bin/env bash
 
 jshint -c tests/jshint.json src/ examples/
+
+if [[ $? != '0' ]]; then
+    echo 'JSHint failed'
+    exit 1
+fi
+
+echo 'JSHint passed'
